# -*- coding: utf-8 -*-
"""Climate_Cred_Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlQoVj6-qcEFsYS1izvZ8_ktE3EUuwXk
"""

import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import requests
import torch.nn.functional as F
from exa_py import Exa
import spacy
from pydantic import BaseModel
from fastapi import FastAPI
from verify_claim import router as verify_router

app = FastAPI()
app.include_router(verify_router)

HF_TOKEN = os.getenv('HF_TOKEN')
C_API_TOKEN = os.getenv('C_API_TOKEN')
MODEL_ID = "RCSCode/Climate_Cred"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = AutoModelForSequenceClassification.from_pretrained(MODEL_ID, token=HF_TOKEN).to(device)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, token=HF_TOKEN)

# Load the English NLP model
nlp = spacy.load("en_core_web_sm")


def perform_nli(claim, evidence):
    """
    Performs NLI analysis and prints the decoded input to verify token separation.
    """
    # Combine claim and evidence using the tokenizer's internal logic for pair encoding
    inputs = tokenizer(claim, evidence, return_tensors='pt', truncation=True, padding=True, max_length=512).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=-1)

    prediction = torch.argmax(probs, dim=-1).item()
    confidence = probs[0][prediction].item() * 100
    return prediction, confidence

def extract_main_subject(text):
    doc = nlp(text)

    # 1. Extract Noun Chunks (useful for keywords)
    chunks = [chunk.text for chunk in doc.noun_chunks]

    # 2. Extract the specific Subject of the sentence
    subjects = [token.text for token in doc if ("subj" in token.dep_)]

    return {
        "main_subjects": subjects,
        "noun_phrases": chunks
    }

def verify_with_Currents(user_claim, num_articles=10):
    # 1. Extract subjects/phrases to use as keywords
    extracted = extract_main_subject(user_claim)

    # Use the first noun phrase (likely the most descriptive subject)
    search_query = extracted['noun_phrases'][0] if extracted['noun_phrases'] else user_claim

    print(f"\nSearching global news for: {search_query}...")
    # 2. Search Currents API
    res = requests.get(
        "https://api.currentsapi.services/v1/search",
        params={
            "keywords": search_query,
            "language": "en",
            "apiKey": C_API_TOKEN
        },
    )

    data = res.json()
    news_data = data.get('news', [])

    # Fallback: if no results, try the first subject word
    if not news_data and extracted['main_subjects']:
        fallback_query = extracted['main_subjects'][0]
        print(f"No results for '{search_query}'. Trying fallback: {fallback_query}...")
        res = requests.get(
            "https://api.currentsapi.services/v1/search",
            params={
                "keywords": fallback_query,
                "language": "en",
                "apiKey": C_API_TOKEN
            },
        )
        news_data = res.json().get('news', [])

    if not news_data:
        return f"No relevant news articles found for '{search_query}'."

    results = []
    label_map = {0: 'REFUTES', 1: 'SUPPORTS', 2: 'NOT_ENOUGH_INFO'}

    # 3. Perform NLI on a controlled number of articles
    for article in news_data[:num_articles]:
        evidence = f"{article['title']}. {article['description']}"
        pred_idx, conf = perform_nli(user_claim, evidence)

        results.append({
            "title": article['title'],
            "verdict": label_map[pred_idx],
            "confidence": f"{conf:.2f}%",
            "url": article['url']
        })

    return pd.DataFrame(results)

def verify_with_gnews(user_claim, num_articles=5):
    # 1. Extract keywords using our existing spaCy function
    extracted = extract_main_subject(user_claim)
    search_query = extracted['noun_phrases'][0] if extracted['noun_phrases'] else user_claim
    print(f"\nSearching GNews for: {search_query}...")

    # 2. GNews API Configuration
    GNEWS_API_KEY = os.getenv('GNEWS_API_KEY')
    url = f"https://gnews.io/api/v4/search?q={search_query}&lang=en&max={num_articles}&apikey={GNEWS_API_KEY}"

    response = requests.get(url)
    data = response.json()
    articles = data.get('articles', [])

    if not articles:
        return f"No results found on GNews for '{search_query}'."

    results = []
    label_map = {0: 'REFUTES', 1: 'SUPPORTS', 2: 'NOT_ENOUGH_INFO'}

    # 3. Perform NLI on each article
    for article in articles:
        # GNews provides 'title' and 'description'
        evidence = f"{article['title']}. {article['description']}"
        pred_idx, conf = perform_nli(user_claim, evidence)

        results.append({
            "source": "GNews",
            "title": article['title'],
            "verdict": label_map[pred_idx],
            "confidence": f"{conf:.2f}%",
            "url": article['url']
        })

    return pd.DataFrame(results)

def verify_with_Exa(user_claim, num_articles=5):
  exa = Exa(os.getenv('EXA_API_KEY'))
  print(f"\nSearching with Exa for: {user_claim}...")
  result_exa = exa.search(
    user_claim,
    num_results = num_articles,
    type = "auto",
    contents = {
      "highlights": True,
      "category": "research paper"
    }
  )

  results = []
  label_map = {0: 'REFUTES', 1: 'SUPPORTS', 2: 'NOT_ENOUGH_INFO'}

  for res in result_exa.results:
      # Get highlights and take only the first sentence for NLI
      full_highlight = " ".join(res.highlights) if res.highlights else ""
      # Simple split by first period to get the first sentence
      evidence = full_highlight.split('. ')[0] + "." if ". " in full_highlight else full_highlight

      pred_idx, conf = perform_nli(user_claim, evidence)

      results.append({
          "source": "Exa",
          "title": res.title,
          "verdict": label_map[pred_idx],
          "confidence": f"{conf:.2f}%",
          "url": res.url,
          "evidence_used": evidence
      })

  return pd.DataFrame(results)

def verify_claim_unified(claim, num_per_source=5):
    print(f"--- Starting Unified Verification for: {claim} ---")
    currents_df = verify_with_Currents(claim, num_articles=num_per_source)
    gnews_df = verify_with_gnews(claim, num_articles=num_per_source)
    exa_df = verify_with_Exa(claim, num_articles=num_per_source)

    all_dfs = []

    # Standardize and collect results
    if isinstance(currents_df, pd.DataFrame):
        currents_df['source'] = 'CurrentsAPI'
        all_dfs.append(currents_df)

    if isinstance(gnews_df, pd.DataFrame):
        all_dfs.append(gnews_df)

    if isinstance(exa_df, pd.DataFrame):
        all_dfs.append(exa_df)

    if not all_dfs:
        return "No results found across any APIs."

    # Combine
    master_df = pd.concat(all_dfs, ignore_index=True)

    # Filter for significant results (optional)
    significant_results = master_df[master_df['verdict'] != 'NOT_ENOUGH_INFO'].copy()

    # Fix for ValueError: The truth value of a Series is ambiguous
    significant_results['evidence_used'] = np.where(
        (significant_results['source'] == 'CurrentsAPI') | (significant_results['source'] == 'GNews'),
        significant_results['title'],
        significant_results['evidence_used']
    )

    return significant_results


@app.get("/")
async def root():
    return {"message": "Welcome to the Climate Claim Verification API!"}